import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "@/components/common/ClientLayout";
import WhatsAppIcon from "@/components/common/whatsapp/WhatsAppIcon";
import localFont from 'next/font/local';

const madeTommyBold = localFont({
  src: [
    {
      path: '../fonts/made/MADE Outer Sans Bold PERSONAL USE.otf',
      weight: '700', 
      style: 'normal',
    },
  ],
  variable: '--font-made-tommy', 
  display: 'swap', 
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Atheko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${madeTommyBold.variable} antialiased`}>
        <ClientLayout>
          {children}
          <WhatsAppIcon />
        </ClientLayout>
      </body>
    </html>
  );
}
